# Generated by Django 5.2.1 on 2025-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='field',
            field=models.CharField(max_length=100),
        ),
    ]
