# Generated by Django 5.2.1 on 2025-06-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
    ]
